services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-1.21-bullseye
    container_name: 2023-adventcalendar-a10a-app
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    ports:
      - 3000:3000
